http://localhost:8080/estudiantes



###

POST http://localhost:8080/estudiantes HTTP/1.1
content-type: application/json

{
    "nombre": "pedro",
    "apellido": "perez",
    "materia": "calculo 1",
    "nota": 100
}


###
PUT http://localhost:8080/estudiantes/1 HTTP/1.1
content-type: application/json

{
    "nombre": "Luis 2.0",
    "apellido": "Eugenio 2.0",
    "materia": "Ciencias 1",
    "nota": 50
}



###
GET http://localhost:8080/estudiantes HTTP/1.1


###
POST http://localhost:8080/estudiantes HTTP/1.1
content-type: application/json

{
    "nombre": "Luis",
    "apellido": "Eugenio",
    "materia": "Estadistica 1",
    "nota": 80
}





###
DELETE http://localhost:8080/estudiantes/2